DROP TABLE IF EXISTS todos;

CREATE TABLE todos (
    id int auto_increment primary key,
    userId int,
    title varchar(250),
    completed bool
);

insert into todos (userId, title, completed) values (1, 'delectus aut autem', false);
insert into todos (userId, title, completed) values (1, 'quis ut nam facilis et officia qui', false);
insert into todos (userId, title, completed) values (1, 'fugiat veniam minus', false);
insert into todos (userId, title, completed) values (1, 'et porro tempora', true);
insert into todos (userId, title, completed) values (1, 'laboriosam mollitia et enim quasi adipisci quia provident illum', false);
insert into todos (userId, title, completed) values (1, 'qui ullam ratione quibusdam voluptatem quia omnis', false);
insert into todos (userId, title, completed) values (1, 'illo expedita consequatur quia in', false);
insert into todos (userId, title, completed) values (1, 'quo adipisci enim quam ut ab', true);
insert into todos (userId, title, completed) values (1, 'molestiae perspiciatis ipsa', false);
insert into todos (userId, title, completed) values (1, 'illo est ratione doloremque quia maiores aut', true);
insert into todos (userId, title, completed) values (1, 'vero rerum temporibus dolor', true);
insert into todos (userId, title, completed) values (1, 'ipsa repellendus fugit nisi', true);
insert into todos (userId, title, completed) values (1, 'et doloremque nulla', false);
insert into todos (userId, title, completed) values (1, 'repellendus sunt dolores architecto voluptatum', true);
insert into todos (userId, title, completed) values (1, 'ab voluptatum amet voluptas', true);
insert into todos (userId, title, completed) values (1, 'accusamus eos facilis sint et aut voluptatem', true);
insert into todos (userId, title, completed) values (1, 'quo laboriosam deleniti aut qui', true);
insert into todos (userId, title, completed) values (1, 'dolorum est consequatur ea mollitia in culpa', false);
insert into todos (userId, title, completed) values (1, 'molestiae ipsa aut voluptatibus pariatur dolor nihil', true);
insert into todos (userId, title, completed) values (1, 'ullam nobis libero sapiente ad optio sint', true);
insert into todos (userId, title, completed) values (2, 'suscipit repellat esse quibusdam voluptatem incidunt', false);
insert into todos (userId, title, completed) values (2, 'distinctio vitae autem nihil ut molestias quo', true);
insert into todos (userId, title, completed) values (2, 'et itaque necessitatibus maxime molestiae qui quas velit', false);
insert into todos (userId, title, completed) values (2, 'adipisci non ad dicta qui amet quaerat doloribus ea', false);
insert into todos (userId, title, completed) values (2, 'voluptas quo tenetur perspiciatis explicabo natus', true);
insert into todos (userId, title, completed) values (2, 'aliquam aut quasi', true);
insert into todos (userId, title, completed) values (2, 'veritatis pariatur delectus', true);
insert into todos (userId, title, completed) values (2, 'nesciunt totam sit blanditiis sit', false);
insert into todos (userId, title, completed) values (2, 'laborum aut in quam', false);
insert into todos (userId, title, completed) values (2, 'nemo perspiciatis repellat ut dolor libero commodi blanditiis omnis', true);
insert into todos (userId, title, completed) values (2, 'repudiandae totam in est sint facere fuga', false);
insert into todos (userId, title, completed) values (2, 'earum doloribus ea doloremque quis', false);
insert into todos (userId, title, completed) values (2, 'sint sit aut vero', false);
insert into todos (userId, title, completed) values (2, 'porro aut necessitatibus eaque distinctio', false);
insert into todos (userId, title, completed) values (2, 'repellendus veritatis molestias dicta incidunt', true);
insert into todos (userId, title, completed) values (2, 'excepturi deleniti adipisci voluptatem et neque optio illum ad', true);
insert into todos (userId, title, completed) values (2, 'sunt cum tempora', false);
insert into todos (userId, title, completed) values (2, 'totam quia non', false);
insert into todos (userId, title, completed) values (2, 'doloremque quibusdam asperiores libero corrupti illum qui omnis', false);
insert into todos (userId, title, completed) values (2, 'totam atque quo nesciunt', true);
insert into todos (userId, title, completed) values (3, 'aliquid amet impedit consequatur aspernatur placeat eaque fugiat suscipit', false);
insert into todos (userId, title, completed) values (3, 'rerum perferendis error quia ut eveniet', false);
insert into todos (userId, title, completed) values (3, 'tempore ut sint quis recusandae', true);
insert into todos (userId, title, completed) values (3, 'cum debitis quis accusamus doloremque ipsa natus sapiente omnis', true);
insert into todos (userId, title, completed) values (3, 'velit soluta adipisci molestias reiciendis harum', false);
insert into todos (userId, title, completed) values (3, 'vel voluptatem repellat nihil placeat corporis', false);
insert into todos (userId, title, completed) values (3, 'nam qui rerum fugiat accusamus', false);
insert into todos (userId, title, completed) values (3, 'sit reprehenderit omnis quia', false);
insert into todos (userId, title, completed) values (3, 'ut necessitatibus aut maiores debitis officia blanditiis velit et', false);
insert into todos (userId, title, completed) values (3, 'cupiditate necessitatibus ullam aut quis dolor voluptate', true);
insert into todos (userId, title, completed) values (3, 'distinctio exercitationem ab doloribus', false);
insert into todos (userId, title, completed) values (3, 'nesciunt dolorum quis recusandae ad pariatur ratione', false);
insert into todos (userId, title, completed) values (3, 'qui labore est occaecati recusandae aliquid quam', false);
insert into todos (userId, title, completed) values (3, 'quis et est ut voluptate quam dolor', true);
insert into todos (userId, title, completed) values (3, 'voluptatum omnis minima qui occaecati provident nulla voluptatem ratione', true);
insert into todos (userId, title, completed) values (3, 'deleniti ea temporibus enim', true);
insert into todos (userId, title, completed) values (3, 'pariatur et magnam ea doloribus similique voluptatem rerum quia', false);
insert into todos (userId, title, completed) values (3, 'est dicta totam qui explicabo doloribus qui dignissimos', false);
insert into todos (userId, title, completed) values (3, 'perspiciatis velit id laborum placeat iusto et aliquam odio', false);
insert into todos (userId, title, completed) values (3, 'et sequi qui architecto ut adipisci', true);
insert into todos (userId, title, completed) values (4, 'odit optio omnis qui sunt', true);
insert into todos (userId, title, completed) values (4, 'et placeat et tempore aspernatur sint numquam', false);
insert into todos (userId, title, completed) values (4, 'doloremque aut dolores quidem fuga qui nulla', true);
insert into todos (userId, title, completed) values (4, 'voluptas consequatur qui ut quia magnam nemo esse', false);
insert into todos (userId, title, completed) values (4, 'fugiat pariatur ratione ut asperiores necessitatibus magni', false);
insert into todos (userId, title, completed) values (4, 'rerum eum molestias autem voluptatum sit optio', false);
insert into todos (userId, title, completed) values (4, 'quia voluptatibus voluptatem quos similique maiores repellat', false);
insert into todos (userId, title, completed) values (4, 'aut id perspiciatis voluptatem iusto', false);
insert into todos (userId, title, completed) values (4, 'doloribus sint dolorum ab adipisci itaque dignissimos aliquam suscipit', false);
insert into todos (userId, title, completed) values (4, 'ut sequi accusantium et mollitia delectus sunt', false);
insert into todos (userId, title, completed) values (4, 'aut velit saepe ullam', false);
insert into todos (userId, title, completed) values (4, 'praesentium facilis facere quis harum voluptatibus voluptatem eum', false);
insert into todos (userId, title, completed) values (4, 'sint amet quia totam corporis qui exercitationem commodi', true);
insert into todos (userId, title, completed) values (4, 'expedita tempore nobis eveniet laborum maiores', false);
insert into todos (userId, title, completed) values (4, 'occaecati adipisci est possimus totam', false);
insert into todos (userId, title, completed) values (4, 'sequi dolorem sed', true);
insert into todos (userId, title, completed) values (4, 'maiores aut nesciunt delectus exercitationem vel assumenda eligendi at', false);
insert into todos (userId, title, completed) values (4, 'reiciendis est magnam amet nemo iste recusandae impedit quaerat', false);
insert into todos (userId, title, completed) values (4, 'eum ipsa maxime ut', true);
insert into todos (userId, title, completed) values (4, 'tempore molestias dolores rerum sequi voluptates ipsum consequatur', true);
insert into todos (userId, title, completed) values (5, 'suscipit qui totam', true);
insert into todos (userId, title, completed) values (5, 'voluptates eum voluptas et dicta', false);
insert into todos (userId, title, completed) values (5, 'quidem at rerum quis ex aut sit quam', true);
insert into todos (userId, title, completed) values (5, 'sunt veritatis ut voluptate', false);
insert into todos (userId, title, completed) values (5, 'et quia ad iste a', true);
insert into todos (userId, title, completed) values (5, 'incidunt ut saepe autem', true);
insert into todos (userId, title, completed) values (5, 'laudantium quae eligendi consequatur quia et vero autem', true);
insert into todos (userId, title, completed) values (5, 'vitae aut excepturi laboriosam sint aliquam et et accusantium', false);
insert into todos (userId, title, completed) values (5, 'sequi ut omnis et', true);
insert into todos (userId, title, completed) values (5, 'molestiae nisi accusantium tenetur dolorem et', true);
insert into todos (userId, title, completed) values (5, 'nulla quis consequatur saepe qui id expedita', true);
insert into todos (userId, title, completed) values (5, 'in omnis laboriosam', true);
insert into todos (userId, title, completed) values (5, 'odio iure consequatur molestiae quibusdam necessitatibus quia sint', true);
insert into todos (userId, title, completed) values (5, 'facilis modi saepe mollitia', false);
insert into todos (userId, title, completed) values (5, 'vel nihil et molestiae iusto assumenda nemo quo ut', true);
insert into todos (userId, title, completed) values (5, 'nobis suscipit ducimus enim asperiores voluptas', false);
insert into todos (userId, title, completed) values (5, 'dolorum laboriosam eos qui iure aliquam', false);
insert into todos (userId, title, completed) values (5, 'debitis accusantium ut quo facilis nihil quis sapiente necessitatibus', true);
insert into todos (userId, title, completed) values (5, 'neque voluptates ratione', false);
insert into todos (userId, title, completed) values (5, 'excepturi a et neque qui expedita vel voluptate', false);
insert into todos (userId, title, completed) values (6, 'explicabo enim cumque porro aperiam occaecati minima', false);
insert into todos (userId, title, completed) values (6, 'sed ab consequatur', false);
insert into todos (userId, title, completed) values (6, 'non sunt delectus illo nulla tenetur enim omnis', false);
insert into todos (userId, title, completed) values (6, 'excepturi non laudantium quo', false);
insert into todos (userId, title, completed) values (6, 'totam quia dolorem et illum repellat voluptas optio', true);
insert into todos (userId, title, completed) values (6, 'ad illo quis voluptatem temporibus', true);
insert into todos (userId, title, completed) values (6, 'praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt', false);
insert into todos (userId, title, completed) values (6, 'a eos eaque nihil et exercitationem incidunt delectus', true);
insert into todos (userId, title, completed) values (6, 'autem temporibus harum quisquam in culpa', true);
insert into todos (userId, title, completed) values (6, 'aut aut ea corporis', true);
insert into todos (userId, title, completed) values (6, 'magni accusantium labore et id quis provident', false);
insert into todos (userId, title, completed) values (6, 'consectetur impedit quisquam qui deserunt non rerum consequuntur eius', false);
insert into todos (userId, title, completed) values (6, 'quia atque aliquam sunt impedit voluptatum rerum assumenda nisi', false);
insert into todos (userId, title, completed) values (6, 'cupiditate quos possimus corporis quisquam exercitationem beatae', false);
insert into todos (userId, title, completed) values (6, 'sed et ea eum', false);
insert into todos (userId, title, completed) values (6, 'ipsa dolores vel facilis ut', true);
insert into todos (userId, title, completed) values (6, 'sequi quae est et qui qui eveniet asperiores', false);
insert into todos (userId, title, completed) values (6, 'quia modi consequatur vero fugiat', false);
insert into todos (userId, title, completed) values (6, 'corporis ducimus ea perspiciatis iste', false);
insert into todos (userId, title, completed) values (6, 'dolorem laboriosam vel voluptas et aliquam quasi', false);
insert into todos (userId, title, completed) values (7, 'inventore aut nihil minima laudantium hic qui omnis', true);
insert into todos (userId, title, completed) values (7, 'provident aut nobis culpa', true);
insert into todos (userId, title, completed) values (7, 'esse et quis iste est earum aut impedit', false);
insert into todos (userId, title, completed) values (7, 'qui consectetur id', false);
insert into todos (userId, title, completed) values (7, 'aut quasi autem iste tempore illum possimus', false);
insert into todos (userId, title, completed) values (7, 'ut asperiores perspiciatis veniam ipsum rerum saepe', true);
insert into todos (userId, title, completed) values (7, 'voluptatem libero consectetur rerum ut', true);
insert into todos (userId, title, completed) values (7, 'eius omnis est qui voluptatem autem', false);
insert into todos (userId, title, completed) values (7, 'rerum culpa quis harum', false);
insert into todos (userId, title, completed) values (7, 'nulla aliquid eveniet harum laborum libero alias ut unde', true);
insert into todos (userId, title, completed) values (7, 'qui ea incidunt quis', false);
insert into todos (userId, title, completed) values (7, 'qui molestiae voluptatibus velit iure harum quisquam', true);
insert into todos (userId, title, completed) values (7, 'et labore eos enim rerum consequatur sunt', true);
insert into todos (userId, title, completed) values (7, 'molestiae doloribus et laborum quod ea', false);
insert into todos (userId, title, completed) values (7, 'facere ipsa nam eum voluptates reiciendis vero qui', false);
insert into todos (userId, title, completed) values (7, 'asperiores illo tempora fuga sed ut quasi adipisci', false);
insert into todos (userId, title, completed) values (7, 'qui sit non', false);
insert into todos (userId, title, completed) values (7, 'placeat minima consequatur rem qui ut', true);
insert into todos (userId, title, completed) values (7, 'consequatur doloribus id possimus voluptas a voluptatem', false);
insert into todos (userId, title, completed) values (7, 'aut consectetur in blanditiis deserunt quia sed laboriosam', true);
insert into todos (userId, title, completed) values (8, 'explicabo consectetur debitis voluptates quas quae culpa rerum non', true);
insert into todos (userId, title, completed) values (8, 'maiores accusantium architecto necessitatibus reiciendis ea aut', true);
insert into todos (userId, title, completed) values (8, 'eum non recusandae cupiditate animi', false);
insert into todos (userId, title, completed) values (8, 'ut eum exercitationem sint', false);
insert into todos (userId, title, completed) values (8, 'beatae qui ullam incidunt voluptatem non nisi aliquam', false);
insert into todos (userId, title, completed) values (8, 'molestiae suscipit ratione nihil odio libero impedit vero totam', true);
insert into todos (userId, title, completed) values (8, 'eum itaque quod reprehenderit et facilis dolor autem ut', true);
insert into todos (userId, title, completed) values (8, 'esse quas et quo quasi exercitationem', false);
insert into todos (userId, title, completed) values (8, 'animi voluptas quod perferendis est', false);
insert into todos (userId, title, completed) values (8, 'eos amet tempore laudantium fugit a', false);
insert into todos (userId, title, completed) values (8, 'accusamus adipisci dicta qui quo ea explicabo sed vero', true);
insert into todos (userId, title, completed) values (8, 'odit eligendi recusandae doloremque cumque non', false);
insert into todos (userId, title, completed) values (8, 'ea aperiam consequatur qui repellat eos', false);
insert into todos (userId, title, completed) values (8, 'rerum non ex sapiente', true);
insert into todos (userId, title, completed) values (8, 'voluptatem nobis consequatur et assumenda magnam', true);
insert into todos (userId, title, completed) values (8, 'nam quia quia nulla repellat assumenda quibusdam sit nobis', true);
insert into todos (userId, title, completed) values (8, 'dolorem veniam quisquam deserunt repellendus', true);
insert into todos (userId, title, completed) values (8, 'debitis vitae delectus et harum accusamus aut deleniti a', true);
insert into todos (userId, title, completed) values (8, 'debitis adipisci quibusdam aliquam sed dolore ea praesentium nobis', true);
insert into todos (userId, title, completed) values (8, 'et praesentium aliquam est', false);
insert into todos (userId, title, completed) values (9, 'ex hic consequuntur earum omnis alias ut occaecati culpa', true);
insert into todos (userId, title, completed) values (9, 'omnis laboriosam molestias animi sunt dolore', true);
insert into todos (userId, title, completed) values (9, 'natus corrupti maxime laudantium et voluptatem laboriosam odit', false);
insert into todos (userId, title, completed) values (9, 'reprehenderit quos aut aut consequatur est sed', false);
insert into todos (userId, title, completed) values (9, 'fugiat perferendis sed aut quidem', false);
insert into todos (userId, title, completed) values (9, 'quos quo possimus suscipit minima ut', false);
insert into todos (userId, title, completed) values (9, 'et quis minus quo a asperiores molestiae', false);
insert into todos (userId, title, completed) values (9, 'recusandae quia qui sunt libero', false);
insert into todos (userId, title, completed) values (9, 'ea odio perferendis officiis', true);
insert into todos (userId, title, completed) values (9, 'quisquam aliquam quia doloribus aut', false);
insert into todos (userId, title, completed) values (9, 'fugiat aut voluptatibus corrupti deleniti velit iste odio', true);
insert into todos (userId, title, completed) values (9, 'et provident amet rerum consectetur et voluptatum', false);
insert into todos (userId, title, completed) values (9, 'harum ad aperiam quis', false);
insert into todos (userId, title, completed) values (9, 'similique aut quo', false);
insert into todos (userId, title, completed) values (9, 'laudantium eius officia perferendis provident perspiciatis asperiores', true);
insert into todos (userId, title, completed) values (9, 'magni soluta corrupti ut maiores rem quidem', false);
insert into todos (userId, title, completed) values (9, 'et placeat temporibus voluptas est tempora quos quibusdam', false);
insert into todos (userId, title, completed) values (9, 'nesciunt itaque commodi tempore', true);
insert into todos (userId, title, completed) values (9, 'omnis consequuntur cupiditate impedit itaque ipsam quo', true);
insert into todos (userId, title, completed) values (9, 'debitis nisi et dolorem repellat et', true);
insert into todos (userId, title, completed) values (10, 'ut cupiditate sequi aliquam fuga maiores', false);
insert into todos (userId, title, completed) values (10, 'inventore saepe cumque et aut illum enim', true);
insert into todos (userId, title, completed) values (10, 'omnis nulla eum aliquam distinctio', true);
insert into todos (userId, title, completed) values (10, 'molestias modi perferendis perspiciatis', false);
insert into todos (userId, title, completed) values (10, 'voluptates dignissimos sed doloribus animi quaerat aut', false);
insert into todos (userId, title, completed) values (10, 'explicabo odio est et', false);
insert into todos (userId, title, completed) values (10, 'consequuntur animi possimus', false);
insert into todos (userId, title, completed) values (10, 'vel non beatae est', true);
insert into todos (userId, title, completed) values (10, 'culpa eius et voluptatem et', true);
insert into todos (userId, title, completed) values (10, 'accusamus sint iusto et voluptatem exercitationem', true);
insert into todos (userId, title, completed) values (10, 'temporibus atque distinctio omnis eius impedit tempore molestias pariatur', true);
insert into todos (userId, title, completed) values (10, 'ut quas possimus exercitationem sint voluptates', false);
insert into todos (userId, title, completed) values (10, 'rerum debitis voluptatem qui eveniet tempora distinctio a', true);
insert into todos (userId, title, completed) values (10, 'sed ut vero sit molestiae', false);
insert into todos (userId, title, completed) values (10, 'rerum ex veniam mollitia voluptatibus pariatur', true);
insert into todos (userId, title, completed) values (10, 'consequuntur aut ut fugit similique', true);
insert into todos (userId, title, completed) values (10, 'dignissimos quo nobis earum saepe', true);
insert into todos (userId, title, completed) values (10, 'quis eius est sint explicabo', true);
insert into todos (userId, title, completed) values (10, 'numquam repellendus a magnam', true);
insert into todos (userId, title, completed) values (10, 'ipsam aperiam voluptates qui', false)